setup_tasks:
 - ifconfig
 
tasks:
 - tox -e py34
 - tox -e py27
 - tox -e flake8
 - tox -e isort
 - coverage combine && coverage xml && coverage report -m
 - tox -e docs

services:
 - docker

coverage:
  path: coverage.xml
  parser: python
